 apiVersion: apps/v1
 kind: Deployment
 metadata:
   name: jenkins-deployment
   namespace: development
   labels:
     app: jenkins
 spec:
   replicas: 1
   selector:
      matchLabels:
        app: jenkins
   template:
     metadata:
       labels:
         app: jenkins
     spec:
      containers:
         - name: jenkins
           image: registry.krugercorp.co.za/jenkins
           ports:
             - containerPort: 8080
             - containerPort: 50000
           volumeMounts:
             - mountPath: /var/jenkins_home
               name: jenkins-home
             - mountPath: /var/run/docker.sock
               name: jenkins-docker-socket
           readinessProbe:
             httpGet:
               path: /login
               port: 8080
             periodSeconds: 30
             timeoutSeconds: 30
             successThreshold: 2
             failureThreshold: 5
      volumes:
        - name: jenkins-home
          hostPath:
            path: /var/snap/microk8s/common/default-storage/jenkins/jenkins-home
            type: Directory
        - name: jenkins-docker-socket
          hostPath:
            path: /var/run/docker.sock
            type: Socket