version: '3'
services:
  jenkins:
    restart: always
    image: "markusdkruger/jenkins:latest"
    ports:
     - "8080:8080"
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - /opt/docker/jenkins:/var/jenkins_home